export const MARKETPLACE_PACKAGING_PHOTO_MAX = 5 * 1024 * 1024
export const MARKETPLACE_PACKAGING_VIDEO_MAX = 50 * 1024 * 1024
export const MARKETPLACE_PACKAGING_PHOTO_MIN = 1
export const MARKETPLACE_PACKAGING_VIDEO_MIN = 1
export const MARKETPLACE_PACKAGING_PHOTO_MAX_COUNT = 5
export const MARKETPLACE_PACKAGING_VIDEO_MAX_COUNT = 2

export const PACKAGING_RESUBMIT_DAYS = 3
export const PACKAGING_ADMIN_SLA_HOURS = 24
