version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: indoteknizi-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: indoteknizi
      POSTGRES_PASSWORD: indoteknizi_dev
      POSTGRES_DB: indoteknizi
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U indoteknizi']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
